In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
train_data = pd.read_csv("/content/drive/My Drive/male_players (legacy).csv")
test_data = pd.read_csv("/content/drive/My Drive/players_22.csv")

<ipython-input-5-1da8758bedf1>:1: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv("/content/drive/My Drive/male_players (legacy).csv")
<ipython-input-5-1da8758bedf1>:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  test_data = pd.read_csv("/content/drive/My Drive/players_22.csv")


In [ ]:
train_data.head()

player_id                                        player_url  fifa_version  \
0     158023                /player/158023/lionel-messi/150002            15   
1      20801  /player/20801/c-ronaldo-dos-santos-aveiro/150002            15   
2       9014                  /player/9014/arjen-robben/150002            15   
3      41236           /player/41236/zlatan-ibrahimovic/150002            15   
4     167495                /player/167495/manuel-neuer/150002            15   

   fifa_update fifa_update_date         short_name  \
0            2       2014-09-18           L. Messi   
1            2       2014-09-18  Cristiano Ronaldo   
2            2       2014-09-18          A. Robben   
3            2       2014-09-18     Z. Ibrahimović   
4            2       2014-09-18           M. Neuer   

                             long_name player_positions  overall  potential  \
0       Lionel Andrés Messi Cuccittini               CF       93         95   
1  Cristiano Ronaldo dos Santos Aveiro           LW, LM       92         92   
2                         Arjen Robben       RM, LM, RW       90         90   
3                   Zlatan Ibrahimović               ST       90         90   
4                   Manuel Peter Neuer               GK       90         90   

   ...   cdm   rdm   rwb    lb   lcb    cb   rcb    rb    gk  \
0  ...  62+3  62+3  62+3  54+3  45+3  45+3  45+3  54+3  15+3   
1  ...  63+3  63+3  63+3  57+3  52+3  52+3  52+3  57+3  16+3   
2  ...  64+3  64+3  64+3  55+3  46+3  46+3  46+3  55+3  14+3   
3  ...  65+3  65+3  61+3  56+3  55+3  55+3  55+3  56+3  17+3   
4  ...  40+3  40+3  36+3  36+3  38+3  38+3  38+3  36+3  87+3   

                                     player_face_url  
0  https://cdn.sofifa.net/players/158/023/15_120.png  
1  https://cdn.sofifa.net/players/020/801/15_120.png  
2  https://cdn.sofifa.net/players/009/014/15_120.png  
3  https://cdn.sofifa.net/players/041/236/15_120.png  
4  https://cdn.sofifa.net/players/167/495/15_120.png  

[5 rows x 110 columns]

In [ ]:
train_data.drop(['player_url', 'fifa_update_date', 'dob', 'club_jersey_number', 'club_loaned_from', 'nationality_id', 'nation_team_id', 'nation_jersey_number', 'release_clause_eur', 'mentality_composure', 'player_face_url'], axis = 1, inplace = True)

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 99 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   player_id                       161583 non-null  int64  
 1   fifa_version                    161583 non-null  int64  
 2   fifa_update                     161583 non-null  int64  
 3   short_name                      161583 non-null  object 
 4   long_name                       161583 non-null  object 
 5   player_positions                161583 non-null  object 
 6   overall                         161583 non-null  int64  
 7   potential                       161583 non-null  int64  
 8   value_eur                       159530 non-null  float64
 9   wage_eur                        159822 non-null  float64
 10  age                             161583 non-null  int64  
 11  height_cm                       161583 non-null  int64  
 12  weight_kg       

In [ ]:
L=[]
L_less=[]
for i in train_data.columns:
  if((train_data[i].isnull().sum())<(0.4*(train_data.shape[0]))):
    L_less.append(i)
  else:
    L.append(i)

In [ ]:
train_data = train_data[L_less]

In [ ]:
numeric_data=train_data.select_dtypes(include=np.number)
non_numeric=train_data.select_dtypes(include = ['object'])

In [ ]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161583 entries, 0 to 161582
Data columns (total 56 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   player_id                       161583 non-null  int64  
 1   fifa_version                    161583 non-null  int64  
 2   fifa_update                     161583 non-null  int64  
 3   overall                         161583 non-null  int64  
 4   potential                       161583 non-null  int64  
 5   value_eur                       159530 non-null  float64
 6   wage_eur                        159822 non-null  float64
 7   age                             161583 non-null  int64  
 8   height_cm                       161583 non-null  int64  
 9   weight_kg                       161583 non-null  int64  
 10  league_id                       159810 non-null  float64
 11  league_level                    158866 non-null  float64
 12  club_team_id    

In [ ]:
numeric_corr = numeric_data.corr()
numeric_corr

player_id  fifa_version  fifa_update  \
player_id                        1.000000      0.433889          NaN   
fifa_version                     0.433889      1.000000          NaN   
fifa_update                           NaN           NaN          NaN   
overall                         -0.368772      0.047487          NaN   
potential                        0.036648      0.092656          NaN   
value_eur                       -0.079574      0.087519          NaN   
wage_eur                        -0.251547     -0.086428          NaN   
age                             -0.640067      0.031996          NaN   
height_cm                       -0.074743      0.018028          NaN   
weight_kg                       -0.174303     -0.019338          NaN   
league_id                        0.156288      0.182871          NaN   
league_level                    -0.034301     -0.000482          NaN   
club_team_id                     0.125486      0.058655          NaN   
club_contract_valid_until_year   0.436874      0.825690          NaN   
weak_foot                       -0.084847      0.008250          NaN   
skill_moves                     -0.035831      0.043317          NaN   
international_reputation        -0.333350     -0.030201          NaN   
pace                             0.138979     -0.001834          NaN   
shooting                        -0.224098      0.013684          NaN   
passing                         -0.302655      0.040809          NaN   
dribbling                       -0.167174      0.053800          NaN   
defending                       -0.174551      0.034927          NaN   
physic                          -0.312010      0.001112          NaN   
attacking_crossing              -0.133231     -0.006268          NaN   
attacking_finishing             -0.080313      0.011061          NaN   
attacking_heading_accuracy      -0.121276     -0.023493          NaN   
attacking_short_passing         -0.121827      0.037100          NaN   
attacking_volleys               -0.161430     -0.028777          NaN   
skill_dribbling                 -0.033548      0.023575          NaN   
skill_curve                     -0.157001      0.000619          NaN   
skill_fk_accuracy               -0.196692     -0.031278          NaN   
skill_long_passing              -0.164881      0.030289          NaN   
skill_ball_control              -0.098412      0.015432          NaN   
movement_acceleration            0.100650     -0.016729          NaN   
movement_sprint_speed            0.095960     -0.024547          NaN   
movement_agility                -0.021815      0.005541          NaN   
movement_reactions              -0.378009      0.006954          NaN   
movement_balance                 0.038822      0.002432          NaN   
power_shot_power                -0.169329      0.053602          NaN   
power_jumping                   -0.160651     -0.012627          NaN   
power_stamina                   -0.069155     -0.011769          NaN   
power_strength                  -0.238232     -0.007094          NaN   
power_long_shots                -0.163927     -0.024680          NaN   
mentality_aggression            -0.211720     -0.005321          NaN   
mentality_interceptions         -0.149043     -0.003430          NaN   
mentality_positioning           -0.083877      0.012214          NaN   
mentality_vision                -0.168734      0.065872          NaN   
mentality_penalties             -0.150468     -0.040897          NaN   
defending_marking_awareness     -0.091955      0.042991          NaN   
defending_standing_tackle       -0.079938      0.010594          NaN   
defending_sliding_tackle        -0.065170      0.005122          NaN   
goalkeeping_diving              -0.086485     -0.000154          NaN   
goalkeeping_handling            -0.089632      0.002465          NaN   
goalkeeping_kicking             -0.085822      0.002967          NaN   
goalkeeping_positioning         -0.095257      0.002688          NaN   


In [ ]:
top_features = numeric_corr['overall'].sort_values(ascending = False).index[1:11]
features = numeric_data[top_features]
final = numeric_data['overall']

In [ ]:
numeric_data.drop('fifa_update', axis = 1)

player_id  fifa_version  overall  potential    value_eur  wage_eur  \
0          158023            15       93         95  100500000.0  550000.0   
1           20801            15       92         92   79000000.0  375000.0   
2            9014            15       90         90   54500000.0  275000.0   
3           41236            15       90         90   52500000.0  275000.0   
4          167495            15       90         90   63500000.0  300000.0   
...           ...           ...      ...        ...          ...       ...   
161578     269011            23       46         61     110000.0     700.0   
161579     269019            23       46         58     110000.0     750.0   
161580     271093            23       46         58     110000.0     500.0   
161581     271555            23       46         70     150000.0     500.0   
161582     271608            23       46         63     110000.0     500.0   

        age  height_cm  weight_kg  league_id  ...  mentality_vision  \
0        27        169         67       53.0  ...                90   
1        29        185         80       53.0  ...                81   
2        30        180         80       19.0  ...                84   
3        32        195         95       16.0  ...                83   
4        28        193         92       19.0  ...                20   
...     ...        ...        ...        ...  ...               ...   
161578   18        180         73     2012.0  ...                42   
161579   19        188         83     2012.0  ...                31   
161580   19        181         73       65.0  ...                40   
161581   17        175         68       65.0  ...                44   
161582   17        180         70      350.0  ...                20   

        mentality_penalties  defending_marking_awareness  \
0                        76                           25   
1                        85                           22   
2                        80                           29   
3                        91                           25   
4                        37                           25   
...                     ...                          ...   
161578                   54                           23   
161579                   31                           50   
161580                   37                           36   
161581                   63                           19   
161582                   25                           50   

        defending_standing_tackle  defending_sliding_tackle  \
0                              21                        20   
1                              31                        23   
2                              26                        26   
3                              41                        27   
4                              25                        25   
...                           ...                       ...   
161578                         21                        25   
161579                         51                        45   
161580                         45                        50   
161581                         17                        14   
161582                         45                        42   

        goalkeeping_diving  goalkeeping_handling  goalkeeping_kicking  \
0                        6                    11                   15   
1                        7                    11                   15   
2                       10                     8                   11   
3                       13                    15                   10   
4                       87                    85                   92   
...                    ...                   ...                  ...   
161578                   9                    13                   13   
161579                   6                    14                    8   
161580                   8                     9                    7   
161581    

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [ ]:
imp = IterativeImputer(max_iter=10, random_state=0)

In [ ]:
numeric_data = pd.DataFrame(np.round(imp.fit_transform(numeric_data)), columns=numeric_data.copy().columns)

In [ ]:
train_data['overall'].isnull().sum()

0

In [ ]:
numeric_data['overall'].isnull().sum()

0

#### NON NUMERIC

In [ ]:
y = non_numeric['league_name']

In [ ]:
y,actual_values = pd.factorize(y)

In [ ]:
non_numeric.drop('league_name', axis = 1, inplace = True)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
for column in non_numeric.columns:
    label_encoder = LabelEncoder()
    non_numeric[column] = label_encoder.fit_transform(non_numeric[column].astype(str))

In [ ]:
onehot_encoder = OneHotEncoder(sparse = False)
integer_encoded = non_numeric[column].reshape(len(non_numeric[column]), 1)
integer_encoded

array([[25],
       [29],
       [20],
       ...,
       [19],
       [24],
       [15]])

In [ ]:
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
X = pd.concat([numeric_data, non_numeric[column]], axis = 1)
X.head()

player_id  fifa_version  fifa_update  overall  potential    value_eur  \
0   158023.0          15.0          2.0     93.0       95.0  100500000.0   
1    20801.0          15.0          2.0     92.0       92.0   79000000.0   
2     9014.0          15.0          2.0     90.0       90.0   54500000.0   
3    41236.0          15.0          2.0     90.0       90.0   52500000.0   
4   167495.0          15.0          2.0     90.0       90.0   63500000.0   

   wage_eur   age  height_cm  weight_kg  ...  mentality_penalties  \
0  550000.0  27.0      169.0       67.0  ...                 76.0   
1  375000.0  29.0      185.0       80.0  ...                 85.0   
2  275000.0  30.0      180.0       80.0  ...                 80.0   
3  275000.0  32.0      195.0       95.0  ...                 91.0   
4  300000.0  28.0      193.0       92.0  ...                 37.0   

   defending_marking_awareness  defending_standing_tackle  \
0                         25.0                       21.0   
1                         22.0                       31.0   
2                         29.0                       26.0   
3                         25.0                       41.0   
4                         25.0                       25.0   

   defending_sliding_tackle  goalkeeping_diving  goalkeeping_handling  \
0                      20.0                 6.0                  11.0   
1                      23.0                 7.0                  11.0   
2                      26.0                10.0                   8.0   
3                      27.0                13.0                  15.0   
4                      25.0                87.0                  85.0   

   goalkeeping_kicking  goalkeeping_positioning  goalkeeping_reflexes   gk  
0                 15.0                     14.0                   8.0   25  
1                 15.0                     14.0                  11.0   29  
2                 11.0                      5.0                  15.0   20  
3                 10.0                      9.0                  12.0   34  
4                 92.0                     90.0                  86.0  252  

[5 rows x 57 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()
scaled_train_data = scaler.fit_transform(X)
scaled_train_data = pd.DataFrame(scaled_train_data, columns = X.columns)

In [ ]:
pd.Series(y).value_counts()

 3     8652
 4     7557
 1     7508
 14    6695
 15    6398
 16    5982
 8     5806
 29    5772
 30    5590
 0     5538
 12    5504
 2     5263
 26    4809
 6     4565
 5     4560
 18    4532
 19    4462
 11    4322
 23    4305
 9     4076
 20    4034
 17    3995
 25    3916
 22    3809
 27    3613
 24    3568
 32    3188
 35    3166
 13    3018
 7     2969
 21    2883
 31    2386
 10    2174
-1     1773
 37    1677
 28     944
 39     581
 38     554
 40     522
 34     424
 36     167
 33     159
 41      56
 42      56
 43      55
Name: count, dtype: int64

#### TRAINING

In [ ]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor

In [ ]:
lr = LinearRegression()
dt = DecisionTreeClassifier(criterion='entropy')
rf = RandomForestRegressor(random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
import pickle as pkl

In [ ]:
for model in (lr, dt, rf): #
  model.fit(Xtrain, Ytrain)
  pkl.dump(model, open('male_players (legacy).csv' + model.__class__.__name__ + '.pkl', 'wb'))
  y_pred = model.predict(Xtest)

  mse = mean_squared_error(Ytest, y_pred)
  r2 = r2_score(Ytest, y_pred)
  print(f"{model} MSE: {mse:.2f}, R2: {r2}")

LinearRegression() MSE: 62.23, R2: 0.4397212031616653
DecisionTreeClassifier(criterion='entropy') MSE: 0.21, R2: 0.9981247241035259
RandomForestRegressor(random_state=42) MSE: 0.16, R2: 0.9985772164481644


In [ ]:
from sklearn.model_selection import GridSearchCV, KFold

In [ ]:
cv=KFold(n_splits=3)
param_rf ={
    "max_depth":[3,5, 6, 12],
    "min_samples_leaf":[1,5,10],
    "min_samples_split":[2,5,10],
    "n_estimators":[100,500,1000]}

In [70]:
model_gs = GridSearchCV(rf, param_rf, cv=cv, scoring="neg_mean_squared_error")

In [ ]:
model_gs.fit(Xtrain, Ytrain)

In [ ]:
pkl.dump(model_gs, open('male_players (legacy)' + model_gs.__class__.__name__ + '.pkl', 'wb'))
y_pred = model_gs.predict(Xtest)
print(model_gs.__class__.__name__, mean_squared_error(y_test, y_pred))

#### TESTING

In [ ]:
test_data.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2     188545  https://sofifa.com/player/188545/robert-lewand...   
3     190871  https://sofifa.com/player/190871/neymar-da-sil...   
4     192985  https://sofifa.com/player/192985/kevin-de-bruy...   

          short_name                            long_name player_positions  \
0           L. Messi       Lionel Andrés Messi Cuccittini       RW, ST, CF   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro           ST, LW   
2     R. Lewandowski                   Robert Lewandowski               ST   
3          Neymar Jr        Neymar da Silva Santos Júnior          LW, CAM   
4       K. De Bruyne                      Kevin De Bruyne          CAM, CM   

   overall  potential    value_eur  wage_eur  age  ...   lcb    cb   rcb  \
0       93         93  103500000.0  560000.0   33  ...  52+3  52+3  52+3   
1       92         92   63000000.0  220000.0   35  ...  54+3  54+3  54+3   
2       91         91  111000000.0  240000.0   31  ...  60+3  60+3  60+3   
3       91         91  132000000.0  270000.0   28  ...  49+3  49+3  49+3   
4       91         91  129000000.0  370000.0   29  ...  69+3  69+3  69+3   

     rb    gk                                    player_face_url  \
0  62+3  19+3  https://cdn.sofifa.net/players/158/023/21_120.png   
1  61+3  20+3  https://cdn.sofifa.net/players/020/801/21_120.png   
2  61+3  19+3  https://cdn.sofifa.net/players/188/545/21_120.png   
3  62+3  20+3  https://cdn.sofifa.net/players/190/871/21_120.png   
4  75+3  21+3  https://cdn.sofifa.net/players/192/985/21_120.png   

                             club_logo_url  \
0  https://cdn.sofifa.net/teams/241/60.png   
1   https://cdn.sofifa.net/teams/45/60.png   
2   https://cdn.sofifa.net/teams/21/60.png   
3   https://cdn.sofifa.net/teams/73/60.png   
4   https://cdn.sofifa.net/teams/10/60.png   

                             club_flag_url  \
0      https://cdn.sofifa.net/flags/es.png   
1      https://cdn.sofifa.net/flags/it.png   
2      https://cdn.sofifa.net/flags/de.png   
3      https://cdn.sofifa.net/flags/fr.png   
4  https://cdn.sofifa.net/flags/gb-eng.png   

                            nation_logo_url  \
0  https://cdn.sofifa.net/teams/1369/60.png   
1  https://cdn.sofifa.net/teams/1354/60.png   
2                                       NaN   
3                                       NaN   
4  https://cdn.sofifa.net/teams/1325/60.png   

                       nation_flag_url  
0  https://cdn.sofifa.net/flags/ar.png  
1  https://cdn.sofifa.net/flags/pt.png  
2  https://cdn.sofifa.net/flags/pl.png  
3  https://cdn.sofifa.net/flags/br.png  
4  https://cdn.sofifa.net/flags/be.png  

[5 rows x 110 columns]

In [ ]:
test_data.drop(['player_url', 'dob', 'club_jersey_number', 'club_joined_from', 'nationality_id', 'nation_team_id', 'nation_jersey_number', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url'], axis = 1, inplace = True)

In [ ]:
T=[]
T_less=[]
for i in test_data.columns:
  if((test_data[i].isnull().sum())<(0.4*(test_data.shape[0]))):
    T_less.append(i)
  else:
    T.append(i)

In [ ]:
test_data = test_data[T_less]

In [ ]:
test_numeric_data=train_data.select_dtypes(include=np.number)
test_non_numeric=train_data.select_dtypes(include = ['object'])

In [ ]:
test_numeric_data.info()

In [ ]:
test_numeric_corr = test_numeric_data.corr()
test_numeric_corr

In [ ]:
top_test_features = test_numeric_corr['overall'].sort_values(ascending = false).index[1:11]
test_features = test_numeric_data[top_features]
final_test = test_numeric_data['overall']

In [ ]:
test_numeric_data.drop('fifa_update', axis = 1)#

In [ ]:
imp = IterativeImputer(max_iter=10, random_state=0)
numeric_data = pd.DataFrame(np.round(imp.fit_transform(test_numeric_data)), columns = test_numeric_data.copy().columns)

In [ ]:
test_data['overall'].isnull().sum()

In [ ]:
test_numeric_data['overall'].isnull().sum()

##### NON NUMERIC: TEST DATASET

In [ ]:
y = test_non_numeric['league_name']#

In [ ]:
y,actual_values = pd.factorize(y)

In [ ]:
test_non_numeric.drop('league_name', axis = 1, inplace = True)#

In [ ]:
for column in test_non_numeric.columns:
    #label_encoder = LabelEncoder()
    test_non_numeric[column] = label_encoder.fit_transform(test_non_numeric[column].astype(str))

In [ ]:
#onehot_encoder = OneHotEncoder(sparse = False)
int_encoded = test_non_numeric[column].reshape(len(test_non_numeric[column]), 1)
int_encoded

In [ ]:
onehot_encoded = onehot_encoder.fit_transform(int_encoded)
print(onehot_encoded)

In [ ]:
X = pd.concat([numeric_data, test_non_numeric[column]], axis = 1)
X.head()

In [ ]:
scaled = StandardScaler()
scaled_test_data = scaled.fit_transform(X)
scaled_test_data = pd.DataFrame(scaled_test_data, columns = X.columns)

In [ ]:
pd.Series(y).value_counts()

#### TRAINING THE TEST DATASET

In [ ]:
#random forest
rf.fit(X_train, y_train)
  #pkl.dump(model, open('players_22' + model.__class__.__name__ + '.pkl', 'wb'))
y_pred = rf.predict(Xtest)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"{model} MSE: {mse:.2f}, R2: {r2}")

##### Tuning

In [ ]:
#cv=KFold(n_splits=3)
#param_rf ={
#    "max_depth":[3,5, 6, 12],
#    "min_samples_leaf":[1,5,10],
#    "min_samples_split":[2,5,10],
#    "n_estimators":[100,500,1000]}

In [ ]:
#model_gs = GridSearchCV(rf, param_rf, cv=cv, scoring="neg_mean_squared_error")
#model_gs.fit(Xtrain, Ytrain)
pkl.dump(model_gs, open('players_22' + model_gs.__class__.__name__ + '.pkl', 'wb'))
#y_pred = model_gs.predict(Xtest)
print(model_gs.__class__.__name__, mean_squared_error(Ytest, y_pred))